Add cpus_per_task parameter and adapt docstrings.
aibasel/lab pull request #98
Opened 2021-06-20 09:42 UTC by galerykaeser

Summary of the changes:
- A new parameter ```cpus_per_task``` was added to the SlurmEnvironment class.
- The docstring examples were adapted, since now the Slurm parameter ```--cpus-per-task``` is not set via the ```extra_options``` parameter of SlurmEnvironment anymore.
- Internally, though, ```cpus_per_task``` is added to ```extra_options```.
- ```cpus_per_task``` is used as a multiplier for the soft memory limit of a Slurm job.

2021-06-20 10:38 UTC, jendrikseipp requested changes
Great work! The pull request is very clean and minimal, I like that. I only have some opinionated comments. Apart from these, it would be great if you could document the new option briefly in the docstring of the constructor.

2021-06-20 10:38 UTC, jendrikseipp commented on lab/environments.py
> +        self.cpus_per_task = cpus_per_task
I think it's best to use `self.cpus_per_task = cpus_per_task or 1` here already.

2021-06-20 10:38 UTC, jendrikseipp commented on lab/environments.py
> +            self.extra_options += f"\n#SBATCH --cpus-per-task={cpus_per_task}"
To be more in line with the other options, please add this line to the template file and pass cpus_per_task when the template is filled.

2021-06-20 10:38 UTC, jendrikseipp commented on lab/environments.py
> +        job_params["soft_memory_limit"] = int(multiplier * memory_per_cpu_kb * 0.98)
When self.cpus_per_task is already defined above, we don't need the `multiplier` variable anymore and can use self.cpus_per_task directly.

2021-06-21 09:30 UTC, galerykaeser commented
Thanks for the review! I implemented all your suggestions.
I think it would make sense to also adapt the docstring of the GridEnvironment class, where ```--cpus-per-task``` is used as an example for the ```extra_options``` parameter:
https://github.com/aibasel/lab/blob/ef140424bd26efa617849a256c22c7425d09f1b0/lab/environments.py#L136-L140
Do you have any suggestions for another [```sbatch``` option](https://slurm.schedmd.com/sbatch.html) that could be used in this showcase?

2021-06-22 09:18 UTC, jendrikseipp commented
Good idea! Let's use --nodelist for this purpose:

Use *extra_options* to pass additional options. The *extra_options* string may contain newlines. Slurm example that uses a given set of nodes (additional nodes will be used if the given ones don't satisfy the resource constraints)::

`extra_options='#SBATCH --nodelist=ase[1-5,7,10]'`

2021-06-22 09:20 UTC, jendrikseipp requested changes
Looks great! I only have some little nitpicks :-)

2021-06-22 09:20 UTC, jendrikseipp commented on lab/data/slurm-job-header.template
> +### Set amount of cores per task.
amount -> number

2021-06-22 09:20 UTC, jendrikseipp commented on lab/environments.py
> +        *cpus_per_task* sets the amount of cores to be allocated per Slurm
amount -> number

2021-06-22 09:20 UTC, jendrikseipp commented on lab/environments.py
> +        task. If it is not used, it defaults to 1.
used -> given

2021-06-23 09:09 UTC, galerykaeser commented
All done! :-)

2021-06-23 17:25 UTC, jendrikseipp requested changes
Thanks! I have one last comment :-) And could you please add the change to the changelog under docs/news.rst (including your name, if you like)?

2021-06-23 17:25 UTC, jendrikseipp commented on lab/environments.py
> +        self.cpus_per_task = cpus_per_task or 1
I think it's best to use the default already in the constructor (instead of `None`).

2021-07-05 15:01 UTC, jendrikseipp commented
I'll do the last small changes quickly, so that I can include this feature in the next release. Thanks for your work!

2021-07-05 15:21 UTC, jendrikseipp commented
I merged the patch locally because I couldn't push to your repo.

2021-07-05 15:21 UTC, closed without merging

2021-07-13 09:14 UTC, galerykaeser commented
> I'll do the last small changes quickly, so that I can include this feature in the next release. Thanks for your work!

You're welcome! :-)